@echo off
title IIA Vehicle System — Master Node Startup
color 0A

echo.
echo =====================================================
echo   IIA VEHICLE IDENTIFICATION SYSTEM
echo   Uninsured Vehicle Detection — IIIT Delhi
echo   DISTRIBUTED MODE (cross-network via ngrok)
echo =====================================================
echo.

set "PROJECT_ROOT=%~dp0"
set "BACKEND_DIR=%PROJECT_ROOT%backend"
set "FRONTEND_DIR=%PROJECT_ROOT%frontend"
set "DATA_DIR=%PROJECT_ROOT%data"

:: ── Detect LAN IP ────────────────────────────────────────────
echo [*] Detecting your IP address...
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4" ^| findstr /v "127.0.0.1"') do (
    set LAN_IP=%%a
    goto :got_ip
)
:got_ip
set LAN_IP=%LAN_IP: =%
if "%LAN_IP%"=="" set LAN_IP=localhost
echo [*] Your IP: %LAN_IP%
echo.

:: ── Check Python ──────────────────────────────────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found. Install from https://python.org/downloads
    pause & exit /b 1
)

:: ── Check Node.js ─────────────────────────────────────────────
where node >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found. Install from https://nodejs.org
    pause & exit /b 1
)

:: ── Distributed Node URLs ────────────────────────────────────
echo =====================================================
echo   DISTRIBUTED DATABASE SETUP
echo.
echo   This laptop (MASTER) owns: capture.db
echo.
echo   Laptop B and C must already be running their
echo   node backend with ngrok. Get the ngrok URLs from
echo   them and enter below.
echo.
echo   If testing locally (all on same machine), just
echo   press Enter to use localhost defaults.
echo =====================================================
echo.

set "NODE_B_URL=http://localhost:8001"
set "NODE_C_URL=http://localhost:8002"

set /p "NODE_B_INPUT=Laptop B ngrok URL (e.g. https://abc.ngrok-free.app): "
if not "%NODE_B_INPUT%"=="" set "NODE_B_URL=%NODE_B_INPUT%"

set /p "NODE_C_INPUT=Laptop C ngrok URL (e.g. https://xyz.ngrok-free.app): "
if not "%NODE_C_INPUT%"=="" set "NODE_C_URL=%NODE_C_INPUT%"

echo.
echo [*] Laptop B node: %NODE_B_URL%
echo [*] Laptop C node: %NODE_C_URL%
echo.

:: ── Install backend dependencies ─────────────────────────────
echo [*] Installing Python dependencies...
cd /d "%BACKEND_DIR%"
python -m pip install -r requirements.txt --quiet
if errorlevel 1 (
    echo [ERROR] pip install failed.
    pause & exit /b 1
)
echo     Done.
echo.

:: ── Seed databases if not already seeded ─────────────────────
if not exist "%DATA_DIR%\capture.db" (
    echo [*] Seeding databases with demo data...
    cd /d "%PROJECT_ROOT%"
    python scripts/seed_databases.py
    echo     Done.
    echo.
) else (
    echo [*] Databases already seeded. Skipping.
    echo.
)

:: ── Install frontend dependencies ────────────────────────────
echo [*] Installing Node.js dependencies...
cd /d "%FRONTEND_DIR%"
call npm install --silent
echo     Done.
echo.

:: ── Write frontend .env ───────────────────────────────────────
echo [*] Writing frontend .env...
(
    echo # Auto-generated by start_server.bat
    echo VITE_API_BASE=http://%LAN_IP%:8000
    echo VITE_NODE_B_URL=%NODE_B_URL%
    echo VITE_NODE_C_URL=%NODE_C_URL%
) > "%FRONTEND_DIR%\.env"
echo     Done.
echo.

:: ── Print info ────────────────────────────────────────────────
echo =====================================================
echo   READY TO START!
echo.
echo   Local access:
echo     Frontend:  http://localhost:5173
echo     Backend:   http://localhost:8000/docs
echo.
echo   Share with others on same WiFi:
echo     http://%LAN_IP%:5173
echo.
echo   For cross-network access, also run ngrok:
echo     ngrok http 8000   (in a separate window)
echo     ngrok http 5173   (in another window)
echo   Then share the ngrok HTTPS URLs.
echo =====================================================
echo.

:: ── Start backend ─────────────────────────────────────────────
echo [*] Starting backend (FastAPI on port 8000)...
start "IIA Backend (FastAPI)" cmd /k "set NODE_B_URL=%NODE_B_URL% && set NODE_C_URL=%NODE_C_URL% && cd /d "%BACKEND_DIR%" && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

:: ── Wait then start frontend ──────────────────────────────────
timeout /t 4 /nobreak >nul

echo [*] Starting frontend (Vite on port 5173)...
start "IIA Frontend (Vite)" cmd /k "cd /d "%FRONTEND_DIR%" && npm run dev -- --host 0.0.0.0"

echo.
echo [*] Both servers are starting in separate windows.
echo [*] Open: http://localhost:5173
echo.
echo Press any key to close this launcher (servers keep running)...
pause >nul
