@echo off
title IIA Vehicle System — Server Startup
color 0A

echo.
echo =====================================================
echo   IIA VEHICLE IDENTIFICATION SYSTEM
echo   Uninsured Vehicle Detection — IIIT Delhi
echo =====================================================
echo.

:: ── Find the project root (same folder as this .bat file) ──────────────────
set "PROJECT_ROOT=%~dp0"
set "BACKEND_DIR=%PROJECT_ROOT%backend"
set "FRONTEND_DIR=%PROJECT_ROOT%frontend"
set "DATA_DIR=%PROJECT_ROOT%data"

:: ── Get LAN IP (skip loopback, get first real adapter) ─────────────────────
echo [*] Detecting your LAN IP address...
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4" ^| findstr /v "127.0.0.1"') do (
    set LAN_IP=%%a
    goto :got_ip
)
:got_ip
set LAN_IP=%LAN_IP: =%

if "%LAN_IP%"=="" (
    echo [!] Could not detect LAN IP. Using localhost.
    set LAN_IP=localhost
)

echo [*] Your LAN IP: %LAN_IP%
echo.

:: ── Write frontend .env with correct LAN IP ───────────────────────────────
echo [*] Configuring frontend...
echo.
echo =====================================================
echo   DISTRIBUTED DATABASE SETUP
echo   This laptop (MASTER) owns: capture.db
echo.
echo   You need Laptop B IP (owns insurance + registration)
echo   You need Laptop C IP (owns theft + ministry)
echo =====================================================
echo.

set "NODE_B_IP=localhost"
set "NODE_C_IP=localhost"

set /p "NODE_B_IP=Enter Laptop B IP (press Enter to use localhost for testing): "
if "%NODE_B_IP%"=="" set "NODE_B_IP=localhost"

set /p "NODE_C_IP=Enter Laptop C IP (press Enter to use localhost for testing): "
if "%NODE_C_IP%"=="" set "NODE_C_IP=localhost"

echo.
echo [*] Laptop B node: http://%NODE_B_IP%:8001
echo [*] Laptop C node: http://%NODE_C_IP%:8002
echo.

:: Set env vars for the backend process
set "NODE_B_URL=http://%NODE_B_IP%:8001"
set "NODE_C_URL=http://%NODE_C_IP%:8002"

(
    echo # Auto-generated by start_server.bat
    echo # Friends should open: http://%LAN_IP%:5173
    echo VITE_API_BASE=http://%LAN_IP%:8000
    echo VITE_NODE_B_URL=http://%NODE_B_IP%:8001
    echo VITE_NODE_C_URL=http://%NODE_C_IP%:8002
) > "%FRONTEND_DIR%\.env"
echo     Written: %FRONTEND_DIR%\.env
echo.

:: ── Check Python ──────────────────────────────────────────────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found! Please install Python 3.10+ and re-run.
    pause
    exit /b 1
)

:: ── Check Node.js ─────────────────────────────────────────────────────────
where node >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js not found! Please install Node.js 18+ and re-run.
    pause
    exit /b 1
)

:: ── Install backend dependencies ──────────────────────────────────────────
echo [*] Installing Python dependencies (this may take a minute first time)...
cd /d "%BACKEND_DIR%"
python -m pip install -r requirements.txt --quiet
if errorlevel 1 (
    echo [ERROR] pip install failed. Check your internet connection.
    pause
    exit /b 1
)
echo     Done!
echo.

:: ── Seed databases if empty ───────────────────────────────────────────────
if not exist "%DATA_DIR%\registration.db" (
    echo [*] Seeding databases with demo data...
    cd /d "%PROJECT_ROOT%"
    python scripts/seed_databases.py
    echo     Done!
    echo.
) else (
    echo [*] Databases already seeded. Skipping seed.
    echo.
)

:: ── Install frontend dependencies ─────────────────────────────────────────
echo [*] Installing Node.js dependencies (first time only)...
cd /d "%FRONTEND_DIR%"
call npm install --silent
echo     Done!
echo.

:: ── Print sharing information ─────────────────────────────────────────────
echo =====================================================
echo   STARTUP COMPLETE!
echo.
echo   YOU (on this laptop):
echo     Frontend:  http://localhost:5173
echo     Backend:   http://localhost:8000
echo     API Docs:  http://localhost:8000/docs
echo.
echo   YOUR FRIENDS (on same WiFi):
echo     Open Chrome/Firefox and go to:
echo     http://%LAN_IP%:5173
echo.
echo   The backend is at:
echo     http://%LAN_IP%:8000
echo =====================================================
echo.
echo [*] Starting backend server (FastAPI)...
echo.

:: ── Start backend in new window ───────────────────────────────────────────
start "IIA Backend (FastAPI)" cmd /k "set NODE_B_URL=%NODE_B_URL% && set NODE_C_URL=%NODE_C_URL% && cd /d "%BACKEND_DIR%" && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

:: ── Wait for backend to be ready ──────────────────────────────────────────
echo [*] Waiting for backend to start (5 seconds)...
timeout /t 5 /nobreak >nul

:: ── Start frontend in new window ─────────────────────────────────────────
echo [*] Starting frontend (Vite)...
start "IIA Frontend (Vite)" cmd /k "cd /d "%FRONTEND_DIR%" && npm run dev -- --host 0.0.0.0"

echo.
echo [*] Both servers are starting in separate windows.
echo [*] Open your browser to http://%LAN_IP%:5173
echo [*] Share that URL with your friends on the same WiFi!
echo.
echo Press any key to close this window (servers keep running)...
pause >nul
